import android.app.Activity;
import android.os.Handler;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.koushikdutta.async.http.callback.RequestCallback;

/**
 * Created by Cookie on 07.05.2016.
 */
public class ApiConfig extends ApiBase{

    private static Gson gson = new GsonBuilder().create();

    // This class is automatically generated by the Floodway System

    // CONFIGURATION
    private final String baseUrl = "http://192.168.2.105:4080/";
    private boolean enableConnectDialog = true;

    // SINGLETON INSTNACE
    public ApiConfig(Activity activity){
        this.activity = activity;
    }
    private static ApiConfig mInstace;
    public static ApiConfig getDefaultInstance(Activity activity){
        if(mInstace == null) {
            mInstace = new ApiConfig(activity);
        }
        mInstace.mountActivity(activity);
        return mInstace;
    }
    public static ApiConfig getDefaultInstance(){
        return mInstace;
    }

    // METHODS USED TO COMMUNICATE WITH ApiBase
    public boolean enableConnectDialog() {
        return enableConnectDialog;
    }
    public String getBaseUrl() { return baseUrl; }
    // INTERNAL CLASS DO NOT CHANGE
    public abstract static class ActionCallback<Result>{
        abstract public void onError(String error);
        abstract public void onResult(Result result);
    }
    // NAMESPACES BELOW


    //REPLACEME//






}
